In [ ]:
# pip install pandas

Requirement already satisfied: pandas in c:\Users\ks836\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\ks836\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\ks836\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\ks836\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\ks836\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\ks836\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# pip install numpy

Requirement already satisfied: numpy in c:\Users\ks836\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.2.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import joblib

In [ ]:
# from sklearn.linear_model import LogisticRegression
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import confusion_matrix
# from sklearn.metrics import classification_report
# from sklearn.metrics import (
#     accuracy_score,
#     precision_score,
#     recall_score,
#     f1_score
# )
# from sklearn.preprocessing import LabelEncoder

In [ ]:
# df = pd.read_csv("D:/heart_disease_prediction/dataset/heart_disease_prediction_300.csv")

NameError: name 'pd' is not defined

In [ ]:
# df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,53,Male,ATA,118,323,0,ST,112,Y,1.0,Flat,1
1,63,Male,TA,156,205,0,LVH,161,N,0.2,Down,1
2,43,Male,ATA,124,210,1,LVH,90,Y,3.0,Down,1
3,75,Female,ATA,93,338,1,ST,138,N,1.0,Up,1
4,60,Male,TA,138,332,1,LVH,95,Y,3.1,Up,1

In [ ]:
# df.tail()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
295,55,Male,ATA,130,238,0,LVH,162,N,3.7,Up,0
296,35,Male,ASY,159,267,1,LVH,143,N,2.0,Up,1
297,68,Male,ATA,176,344,1,Normal,195,N,1.6,Flat,1
298,70,Male,NAP,127,301,0,LVH,157,Y,4.2,Up,1
299,64,Male,NAP,131,122,1,ST,83,N,4.9,Up,1

In [ ]:
# df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             300 non-null    int64
 1   Sex             300 non-null    object
 2   ChestPainType   300 non-null    object
 3   RestingBP       300 non-null    int64
 4   Cholesterol     300 non-null    int64
 5   FastingBS       300 non-null    int64
 6   RestingECG      300 non-null    object
 7   MaxHR           300 non-null    int64
 8   ExerciseAngina  300 non-null    object
 9   Oldpeak         300 non-null    float64
 10  ST_Slope        300 non-null    object
 11  HeartDisease    300 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 28.3+ KB

In [ ]:
# df.shape

(300, 12)

In [ ]:
# df.isna().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

In [ ]:
# df.duplicated().sum()

np.int64(0)

In [ ]:
# le = LabelEncoder()

In [ ]:
# df["Sex"] = le.fit_transform(df["Sex"])
# df["ChestPainType"] = le.fit_transform(df["ChestPainType"])
# df["RestingECG"] = le.fit_transform(df["RestingECG"])
# df["ExerciseAngina"] = le.fit_transform(df['ExerciseAngina'])
# df["ST_Slope"]=le.fit_transform(df["ST_Slope"])

In [ ]:
# df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,53,1,1,118,323,0,2,112,1,1.0,1,1
1,63,1,3,156,205,0,0,161,0,0.2,0,1
2,43,1,1,124,210,1,0,90,1,3.0,0,1
3,75,0,1,93,338,1,2,138,0,1.0,2,1
4,60,1,3,138,332,1,0,95,1,3.1,2,1

In [ ]:
# df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,53,1,1,118,323,0,2,112,1,1.0,1,1
1,63,1,3,156,205,0,0,161,0,0.2,0,1
2,43,1,1,124,210,1,0,90,1,3.0,0,1
3,75,0,1,93,338,1,2,138,0,1.0,2,1
4,60,1,3,138,332,1,0,95,1,3.1,2,1

In [ ]:
# df.tail()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
295,55,1,1,130,238,0,0,162,0,3.7,2,0
296,35,1,0,159,267,1,0,143,0,2.0,2,1
297,68,1,1,176,344,1,1,195,0,1.6,1,1
298,70,1,2,127,301,0,0,157,1,4.2,2,1
299,64,1,2,131,122,1,2,83,0,4.9,2,1

In [ ]:
# x = df.drop("HeartDisease",axis=1)

In [ ]:
# y =df["HeartDisease"]

In [ ]:
# X_train ,X_test , y_train , y_test = train_test_split(x,y,train_size=0.8,random_state=42)

In [ ]:
# X_train

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
232,46,1,2,160,242,0,1,165,1,3.8,1
59,53,0,0,117,242,1,2,134,1,1.6,2
6,33,1,0,108,320,0,0,94,0,5.5,0
185,33,1,3,126,282,1,1,170,1,5.1,2
173,60,0,2,168,276,0,0,183,1,4.8,0
...,...,...,...,...,...,...,...,...,...,...,...
188,41,1,3,162,121,0,1,174,1,3.0,2
71,71,1,0,99,213,0,1,112,1,1.3,2
106,70,1,1,173,291,0,0,133,1,3.1,1
270,67,0,3,146,129,1,1,191,1,5.8,1
102,59,1,3,164,257,0,2,109,1,5.9,0

In [ ]:
# X_test

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
203,33,0,3,136,229,0,0,196,0,1.1,1
266,65,0,1,173,310,0,2,135,0,5.7,0
152,60,1,0,115,247,1,2,145,1,4.6,2
9,50,1,0,164,358,1,0,172,0,1.5,1
233,51,0,0,143,124,0,2,151,0,4.4,2
226,50,1,1,164,358,0,2,103,1,5.6,2
196,62,1,2,126,267,1,2,160,0,3.2,2
109,32,1,1,113,205,0,0,136,1,5.2,0
5,33,1,0,108,320,0,0,94,0,5.5,0
175,66,1,3,149,137,0,1,196,1,5.2,1
237,74,0,3,100,237,0,1,193,0,1.4,0
57,34,0,1,120,187,1,1,72,1,3.0,2
218,76,0,3,112,133,1,2,91,0,5.1,0
45,73,1,3,147,154,1,0,128,1,5.4,2
182,58,0,1,143,346,1,2,149,1,1.0,0
221,71,1,1,105,249,0,0,81,0,0.7,1
289,52,1,1,103,188,1,0,72,0,5.3,2
211,36,1,3,180,262,0,0,75,0,5.5,0
148,44,0,3,156,267,1,0,81,0,2.1,0
165,32,1,3,173,145,0,1,176,0,4.0,2
78,73,0,3,111,276,0,2,84,0,0.7,1
113,37,0,3,161,333,0,2,166,1,1.0,1
249,46,1,3,148,189,0,0,74,0,0.7,1
250,35,1,2,178,196,1,2,165,1,4.3,1
104,40,1,3,117,272,0,1,137,0,3.6,0
42,74,1,3,104,132,1,1,134,1,5.1,1
281,74,1,3,99,141,0,1,111,0,0.5,1
295,55,1,1,130,238,0,0,162,0,3.7,2
157,31,0,3,150,206,0,1,189,1,3.1,2
238,49,1,3,176,270,1,1,92,0,1.6,0
17,72,1,1,92,320,1,1,152,0,1.1,2
164,76,0,1,168,191,1,0,132,0,5.7,2
33,41,0,3,107,227,0,2,150,0,3.8,0
24,69,1,0,127,154,0,0,103,1,4.0,1
215,51,0,2,174,240,1,2,129,0,5.6,0
119,58,1,0,134,300,0,2,88,0,0.4,1
7,74,0,3,98,242,1,2,70,1,0.9,0
90,49,0,1,97,317,1,2,83,1,4.4,1
46,36,1,3,132,205,1,2,92,0,3.5,1
73,32,1,2,114,272,0,0,122,0,5.7,2
93,46,0,0,117,307,0,0,189,0,5.6,1
76,35,1,0,93,185,0,1,86,1,3.6,0
286,68,1,0,139,359,0,1,157,0,2.8,1
60,50,1,3,170,148,1,1,194,0,3.0,0
77,40,1,3,105,342,1,1,104,0,1.1,1
63,42,0,3,93,134,1,2,184,0,2.6,0
234,76,0,0,170,205,1,0,129,1,2.2,0
229,36,0,2,155,238,1,2,169,0,3.5,0
111,51,1,3,101,184,0,2,120,0,4.0,0
231,46,1,2,160,242,0,1,165,1,3.8,1
180,76,1,1,146,244,1,2,112,0,1.2,1
144,65,0,2,91,136,1,1,183,1,5.9,1
239,32,0,0,127,125,0,0,192,0,5.1,1
75,42,1,1,174,140,0,1,161,0,0.7,2
297,68,1,1,176,344,1,1,195,0,1.6,1
278,64,0,0,145,167,0,0,142,1,2.5,1
97,32,0,0,125,296,1,1,99,0,1.8,2
92,33,1,0,163,248,0,2,179,1,4.4,1
192,66,0,3,145,255,1,2,144,0,5.9,2
25,43,1,1,157,172,0,0,172,1,3.1,2

In [ ]:
# model = LogisticRegression()

In [ ]:
# model.fit(X_train,y_train)

c:\Users\ks836\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
# y_pred = model.predict(X_test)

In [ ]:
# y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [ ]:
# print("actual disease: ",y_test)
# print("prediction disease: ",y_pred)

actual disease:  203    0
266    1
152    0
9      1
233    1
226    0
196    1
109    0
5      1
175    1
237    0
57     0
218    1
45     0
182    1
221    1
289    0
211    0
148    0
165    1
78     1
113    1
249    1
250    0
104    1
42     1
281    0
295    0
157    0
238    0
17     0
164    1
33     0
24     1
215    1
119    0
7      1
90     0
46     1
73     1
93     1
76     0
286    1
60     1
77     1
63     1
234    0
229    1
111    1
231    1
180    1
144    1
239    1
75     1
297    1
278    1
97     1
92     1
192    1
25     1
Name: HeartDisease, dtype: int64
prediction disease:  [0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1
 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1]

In [ ]:
# accuracy = accuracy_score(y_test,y_pred)
# precision = precision_score(y_test,y_pred)
# recall = recall_score(y_test,y_pred)
# f1_Score = f1_score(y_test,y_pred)

In [ ]:
# print("accuracy score:- ",accuracy)
# print("precision_score:- ",precision)
# print("recall_score:- ",recall)
# print("f1_score:- ",f1_Score)

accuracy score:-  0.7833333333333333
precision_score:-  0.76
recall_score:-  0.9743589743589743
f1_score:-  0.8539325842696629

In [ ]:
# cm = confusion_matrix(y_test,y_pred)
# cm

array([[ 9, 12],
       [ 1, 38]])

In [ ]:
# report = (classification_report(y_test,y_pred))

In [ ]:
# print(report)

              precision    recall  f1-score   support

           0       0.90      0.43      0.58        21
           1       0.76      0.97      0.85        39

    accuracy                           0.78        60
   macro avg       0.83      0.70      0.72        60
weighted avg       0.81      0.78      0.76        60

In [ ]:
# joblib.dump(model,"HeartDisease_model.joblib")

['HeartDisease_model.joblib']

In [ ]:
# HDM = joblib.load("HeartDisease_model.joblib")

In [ ]:
# HDM.predict([[63,1,3,156,205,0,0,161,0,0.2,0]])

c:\Users\ks836\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [ ]:
# HDM.predict([[55,1,1,130,38,0,0	,62,0,3.7,2]])

c:\Users\ks836\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [ ]:
# metrics = {
#     "Accuracy":accuracy,
#     "Precision":precision,
#     "Recall":recall,
#     "F1 Score": f1_Score
# }

In [ ]:
# joblib.dump(metrics, "HeartDisease_metrics.joblib")

['HeartDisease_metrics.joblib']

In [ ]:
# joblib.dump(cm,"confusion_matrix.joblib")

['confusion_matrix.joblib']

In [ ]:
# joblib.dump(report,"classification_report.joblib")

['classification_report.joblib']

In [ ]:
#